### ISSUE TITLE
Auth Error

### ISSUE THREAD

**Issue by IamNomadSauce** [mickomagallanes/kucoin-futures-node-api#2]
I have confirmed that my passphrase, key and secret are correct but when I initiate the API instance it gives me a 401 error 'invalid KC-API-PASSPHRASE'
I have this same api working with python but not js, so its not my authentication values.

**Comment by kori256** [comment]
You need to pass the header 
`header.headers['KC-API-KEY-VERSION'] = 2`

#3

**Comment by IamNomadSauce** [comment]
I added the header and am still getting the same error.  I see that it is
still trying to connect to V1 of the API.  I was supposed to replace it in
the kucoin.js in the nodemodules folder?

**Comment by IamNomadSauce** [comment]
disregard, i restarted the computer and everything worked fine
