### ISSUE TITLE
getAllPositions returns undefined

### ISSUE THREAD

**Issue by IamNomadSauce** [mickomagallanes/kucoin-futures-node-api#4]
all of the other endpoints work fine but getAllPositions() returns 'Cannot read property length of undefined' undefined despite having multiple positions.  getPosition() with specific symbols works just fine and returns appropriate data.

**Comment by mickomagallanes** [comment]
Hi, 

I have updated the files. I changed something in the formatQuery(), I tested it and the error 401 finally shown. Please remind me if the issue still persists.

Thanks

**Comment by corywolfe99** [comment]
Issue failed in version 1.0.2
Issue resolved in version 1.0.5

This issue can be closed.
Thank you
